insert into songs (Artist, Title, Genre) values ('Hayden Knight', 'Golden Glade', 'jazz');
insert into songs (Artist, Title, Genre) values ('Ethan Blackwood', 'Enchanted Forest', 'reggae');
insert into songs (Artist, Title, Genre) values ('Nora Hayes', 'Sunset Symphony', 'reggae');
insert into songs (Artist, Title, Genre) values ('Reese Bryant', 'Crimson Sunset', 'R&B');
insert into songs (Artist, Title, Genre) values ('Rowan Taylor', 'Whispering Waters', 'classical');
insert into songs (Artist, Title, Genre) values ('Bailey Fox', 'Starry Skies', 'indie');
insert into songs (Artist, Title, Genre) values ('Casey Phillips', 'Oceanic Overture', 'hip hop');
insert into songs (Artist, Title, Genre) values ('Jamie Knight', 'Whimsical Whispers', 'rock');
insert into songs (Artist, Title, Genre) values ('Casey Blackwood', 'Golden Horizon', 'country');
insert into songs (Artist, Title, Genre) values ('Parker Summers', 'Dreamscape Symphony', 'blues');
insert into songs (Artist, Title, Genre) values ('Sydney Cooper', 'Serenade of the Stars', 'rap');
insert into songs (Artist, Title, Genre) values ('Taylor Rivers', 'Echoes of Eternity', 'rap');
insert into songs (Artist, Title, Genre) values ('Cameron Brooks', 'Mystic Mirage', 'folk');
insert into songs (Artist, Title, Genre) values ('Jesse Reed', 'Moonlit Sonata', 'folk');
insert into songs (Artist, Title, Genre) values ('Reese Reed', 'Sunset Serenade', 'classical');
insert into songs (Artist, Title, Genre) values ('Jamie Knight', 'Electric Dreams', 'reggae');
insert into songs (Artist, Title, Genre) values ('Hayden Turner', 'Emerald Enchantment', 'rap');
insert into songs (Artist, Title, Genre) values ('Hayden Knight', 'Starry Skies', 'pop');
insert into songs (Artist, Title, Genre) values ('Jordan Fox', 'Whispering Whispers', 'electronic');
insert into songs (Artist, Title, Genre) values ('Jesse Reed', 'Midnight Melody', 'punk');
insert into songs (Artist, Title, Genre) values ('Casey Blackwood', 'Mountain Serenade', 'blues');
insert into songs (Artist, Title, Genre) values ('Dakota Mitchell', 'Harmony in the Hills', 'classical');
insert into songs (Artist, Title, Genre) values ('Parker Summers', 'Whispering Whispers', 'country');
insert into songs (Artist, Title, Genre) values ('Dylan Knight', 'Celestial Serenity', 'electronic');
insert into songs (Artist, Title, Genre) values ('Rory Brooks', 'Whimsical Whispers', 'blues');
insert into songs (Artist, Title, Genre) values ('Reese Bryant', 'Whispering Whispers', 'rock');
insert into songs (Artist, Title, Genre) values ('Reese Reed', 'Sapphire Skies', 'rock');
insert into songs (Artist, Title, Genre) values ('Hayden Knight', 'Serenade of the Stars', 'classical');
insert into songs (Artist, Title, Genre) values ('Jamie Knight', 'Sunset Silhouette', 'R&B');
insert into songs (Artist, Title, Genre) values ('Jesse Reed', 'Mystic Meadows', 'pop');
insert into songs (Artist, Title, Genre) values ('Bailey Evans', 'Mystic Mirage', 'reggae');
insert into songs (Artist, Title, Genre) values ('Kai Morgan', 'Harbor Haven', 'reggae');
insert into songs (Artist, Title, Genre) values ('Alex Summers', 'Sapphire Sunset', 'rap');
insert into songs (Artist, Title, Genre) values ('Rory Brooks', 'Serenade of the Stars', 'classical');
insert into songs (Artist, Title, Genre) values ('Alex Summers', 'Oceanic Overture', 'jazz');
insert into songs (Artist, Title, Genre) values ('Morgan Brooks', 'Twilight Tango', 'folk');
insert into songs (Artist, Title, Genre) values ('Casey Phillips', 'City Lights', 'hip hop');
insert into songs (Artist, Title, Genre) values ('Taylor Rivers', 'Whispering Waves', 'folk');
insert into songs (Artist, Title, Genre) values ('Jordan Fox', 'Harbor Hues', 'country');
insert into songs (Artist, Title, Genre) values ('Rowan Taylor', 'Moonlit Melody', 'folk');
insert into songs (Artist, Title, Genre) values ('Reese Bryant', 'Sunset Silhouettes', 'R&B');
insert into songs (Artist, Title, Genre) values ('Taylor Rivers', 'Whispers in the Wind', 'indie');
insert into songs (Artist, Title, Genre) values ('Quinn Parker', 'Whimsical Waltz', 'blues');
insert into songs (Artist, Title, Genre) values ('Dylan Knight', 'Silver Lining', 'electronic');
insert into songs (Artist, Title, Genre) values ('Rory Brooks', 'Whispering Willows', 'rap');
insert into songs (Artist, Title, Genre) values ('Alex Summers', 'Sunset Silhouettes', 'reggae');
insert into songs (Artist, Title, Genre) values ('Emery Wells', 'Moonlit Magic', 'indie');
insert into songs (Artist, Title, Genre) values ('Reese Reed', 'Mountain Serenade', 'punk');
insert into songs (Artist, Title, Genre) values ('Jordan Clarke', 'Twilight Tempest', 'pop');
insert into songs (Artist, Title, Genre) values ('Cameron Brooks', 'Majestic Mountains', 'punk');
insert into songs (Artist, Title, Genre) values ('Cameron Brooks', 'Whimsical Whispers', 'punk');
insert into songs (Artist, Title, Genre) values ('Samantha Rivers', 'Dreamscape Symphony', 'hip hop');
insert into songs (Artist, Title, Genre) values ('Bailey Blackwood', 'Golden Glade', 'rap');
insert into songs (Artist, Title, Genre) values ('Morgan Sullivan', 'Moonlit Magic', 'R&B');
insert into songs (Artist, Title, Genre) values ('Jamie Morgan', 'Dreamscape Symphony', 'electronic');
insert into songs (Artist, Title, Genre) values ('Reese Reed', 'Whispering Pines', 'hip hop');
insert into songs (Artist, Title, Genre) values ('Riley West', 'Firefly Waltz', 'indie');
insert into songs (Artist, Title, Genre) values ('Rory Brooks', 'Summer Breeze', 'rap');
insert into songs (Artist, Title, Genre) values ('Kai Morgan', 'Sapphire Sunset', 'classical');
insert into songs (Artist, Title, Genre) values ('Cameron Brooks', 'Mystic Mirage', 'rap');
insert into songs (Artist, Title, Genre) values ('Bailey Fox', 'Mystic Meadows', 'R&B');
insert into songs (Artist, Title, Genre) values ('Riley West', 'Starry Serenade', 'reggae');
insert into songs (Artist, Title, Genre) values ('Jordan Fox', 'Dancing Shadows', 'rock');
insert into songs (Artist, Title, Genre) values ('Casey Blackwood', 'Firefly Waltz', 'electronic');
insert into songs (Artist, Title, Genre) values ('Hayden Turner', 'Mountain Serenade', 'hip hop');
insert into songs (Artist, Title, Genre) values ('Reese Reed', 'Sapphire Serenade', 'blues');
insert into songs (Artist, Title, Genre) values ('Rory Brooks', 'Azure Serenade', 'rap');
insert into songs (Artist, Title, Genre) values ('Morgan Brooks', 'Amber Dreams', 'rock');
insert into songs (Artist, Title, Genre) values ('Jordan Clarke', 'Whispering Whispers', 'rap');
insert into songs (Artist, Title, Genre) values ('Nora Hayes', 'Whimsical Whispers', 'country');
insert into songs (Artist, Title, Genre) values ('Reese Summers', 'Whispering Waves', 'metal');
insert into songs (Artist, Title, Genre) values ('Bailey Fox', 'Golden Glade', 'R&B');
insert into songs (Artist, Title, Genre) values ('Alex Summers', 'Sapphire Sunset', 'punk');
insert into songs (Artist, Title, Genre) values ('Taylor Parker', 'Midnight Melody', 'folk');
insert into songs (Artist, Title, Genre) values ('Hayden Knight', 'Celestial Serenity', 'jazz');
insert into songs (Artist, Title, Genre) values ('Emery Wells', 'Harmony in the Hills', 'pop');
insert into songs (Artist, Title, Genre) values ('Alex Summers', 'Mystical Moonlight', 'jazz');
insert into songs (Artist, Title, Genre) values ('Aria Summers', 'Dancing Shadows', 'jazz');
insert into songs (Artist, Title, Genre) values ('Kai Morgan', 'Emerald Echo', 'metal');
insert into songs (Artist, Title, Genre) values ('Dylan Knight', 'Harbor Haven', 'classical');
insert into songs (Artist, Title, Genre) values ('Taylor Parker', 'Dancing Shadows', 'electronic');
insert into songs (Artist, Title, Genre) values ('Jordan Fox', 'Emerald Enchantment', 'punk');
insert into songs (Artist, Title, Genre) values ('Sydney Cooper', 'Oceanic Odyssey', 'jazz');
insert into songs (Artist, Title, Genre) values ('Jamie Knight', 'City Lights', 'rock');
insert into songs (Artist, Title, Genre) values ('Jamie Knight', 'Dreamscape Symphony', 'punk');
insert into songs (Artist, Title, Genre) values ('Dylan Knight', 'Dancing Shadows', 'rap');
insert into songs (Artist, Title, Genre) values ('Dylan Knight', 'Sapphire Shores', 'reggae');
insert into songs (Artist, Title, Genre) values ('Jesse Reed', 'Midnight Melody', 'punk');
insert into songs (Artist, Title, Genre) values ('Parker Reed', 'Lavender Lullaby', 'punk');
insert into songs (Artist, Title, Genre) values ('Alexis Campbell', 'Crystal Waters', 'metal');
insert into songs (Artist, Title, Genre) values ('Casey Blackwood', 'Whispers in the Wind', 'pop');
insert into songs (Artist, Title, Genre) values ('Jamie Knight', 'Amber Dreams', 'punk');
insert into songs (Artist, Title, Genre) values ('Avery Brooks', 'Sunset Serenade', 'reggae');
insert into songs (Artist, Title, Genre) values ('Parker Rivers', 'Whispering Whispers', 'blues');
insert into songs (Artist, Title, Genre) values ('Jordan Hayes', 'Whispering Winds', 'jazz');
insert into songs (Artist, Title, Genre) values ('Alex Riley', 'Midnight Melody', 'hip hop');
insert into songs (Artist, Title, Genre) values ('Rory Brooks', 'Tropical Twilight', 'pop');
insert into songs (Artist, Title, Genre) values ('Hayden Knight', 'Golden Horizon', 'folk');
insert into songs (Artist, Title, Genre) values ('Taylor Parker', 'Whispering Waters', 'classical');
insert into songs (Artist, Title, Genre) values ('Taylor Rivers', 'Harbor Haven', 'electronic');
